version: '3.8'

services:
  order-service:
    build:
      context: .
      dockerfile: ftgo-order-service/Dockerfile  # Path to the Dockerfile for module1
    ports:
      - "8081:8080"  # Map port 8080 inside the container to 8081 on localhost
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - consumer-service

  consumer-service:
    build:
      context: .
      dockerfile: ftgo-consumer-service/Dockerfile  # Path to the Dockerfile for module2
    ports:
      - "8082:8080"  # Map port 8080 inside the container to 8082 on localhost
    environment:
      SPRING_PROFILES_ACTIVE: dev